# Generated by Django 5.1.15 on 2026-02-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='closing',
            field=models.TextField(blank=True, verbose_name='Cierre / Conclusión'),
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Máximo 300 caracteres. Se usa en meta tags y como descripción en buscadores.', max_length=300, verbose_name='Resumen (excerpt) para SEO y meta description'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Destacado'),
        ),
        migrations.AddField(
            model_name='post',
            name='lead',
            field=models.TextField(blank=True, verbose_name='Gorro / Introducción'),
        ),
        migrations.AddField(
            model_name='post',
            name='reading_time',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Tiempo de lectura (minutos)'),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado')], default='draft', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='Contenido principal'),
        ),
    ]
